# docker-compose.yml

services:
  haciendola-frontend:
    container_name: haciendola-frontend
    # The name of the image that will be created when building this container
    image: haciendola-frontend
    build: .
    environment:
      # Internal server error messages will not send stacktrace to the browser in production
      NODE_ENV: production
      PUBLIC_BACKEND_HOST: haciendol-backend
      PUBLIC_BACKEND_PORT: 3006
    # Points to a file with the sensitive environment variables
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - haciendola-network

networks:
  haciendola-network:
    external: true
